### ISSUE TITLE
Error with dw_export_chart()

### ISSUE THREAD

**Issue by shamahutoto** [munichrocker/DatawRappr#43]
Hi, when trying to run

aaa_table<- dw_export_chart("IX7iJ",
                            type = "png") 

I get the error `Error: API did not return json`
Just wondering if this an isolated problem? I can update charts using dw_data_to_chart so don't think its an authentication issue.

**Comment by munichrocker** [comment]
Hey @shamahutoto,

I could reproduce the error. The returned type from the API is in format `application/octet-stream`, while DatawRappr expects something like `image/png`.

I added a possible fix which allows a response type `application/octet-stream`.

Could you please update DatawRappr and try again?

Thanks!

**Comment by shamahutoto** [comment]
@munichrocker thank you that worked
