### ISSUE TITLE
Error: object 'parsed' not found

### ISSUE THREAD

**Issue by chrismp** [munichrocker/DatawRappr#51]
On my Arch Linux remote server, with R v4.0.2, when I run this code...

```
  dw_edit_chart(
    chart_id = "MY_CHART_ID",
    api_key = "MY API KEY"
  )
```

... I get this error ...

```
Error in sprintf("Datawrapper API request failed [%s]\n%s", httr::status_code(r),  : 
  object 'parsed' not found
Calls: dw_edit_chart -> dw_handle_errors

```

**Comment by munichrocker** [comment]
Hey @chrismp!
Can you verify you're running the most recent version of Datawrappr on your server? I remember having that issue some time ago, but it was supposed to be fixed.

**Comment by chrismp** [comment]
@munichrocker How would I check the versions of the package installed?

**Comment by chrismp** [comment]
@munichrocker I've got v1.1.3 installed.

**Comment by munichrocker** [comment]
I guess the most straightforward way would be to simply rerun `devtools::install_github("munichrocker/DatawRappr")` as there might be a code change between official releases. This would install the most recent version from this repo.

There is a possible solution to this included in a commit I've just made (https://github.com/munichrocker/DatawRappr/commit/be750531cb1c0294e62492b958c431690f0ecced). Could you please retry? (The error is only displayed if there's an API-Error. That might limit reproducibility)

**Comment by chrismp** [comment]
That seemed to do it. The error message I get when running the code now says:

```
Error: Datawrapper API request failed [401]
Invalid authentication credentials
```

**Comment by munichrocker** [comment]
Thanks!
