### ISSUE TITLE
Linux: dw_data_to_chart -> error

### ISSUE THREAD

**Issue by nicoschreibt** [munichrocker/DatawRappr#53]
When I run a Script with dw_data_to_chart() on Windows it runs perfectly. However, when I run the same script on my Raspberry Pi I get: 
"There has been an error in the upload process. Statuscode of the response: 404TRUE"
What am I doing wrong?

**Comment by munichrocker** [comment]
404 is a `Not Found` error. Is your Pi connected to the internet?
If the script is exactly the same as on your Windows machine, the url to the chart should be fine. Otherwise, 404 could also point to a `chart_id` that doesn't exist.

**Comment by nicoschreibt** [comment]
> 404 is a `Not Found` error. Is your Pi connected to the internet?
> If the script is exactly the same as on your Windows machine, the url to the chart should be fine. Otherwise, 404 could also point to a `chart_id` that doesn't exist.

Thx for your fast reply! 
I know 404 and yes, Raspi is connected to the internet. I use it as a server. That is why I'm asking here  =).
I uploaded the script to Raspi with sftp so everything is 100% the same. Also, the chart exists ("[BVA33](https://datawrapper.dwcdn.net/BVA33/3/)") and I'm having the same issue with several different scripts.

**Comment by nicoschreibt** [comment]
Solved. I had a problem with datawrapper_auth() and never found it because overwrite was F. Thx for your help anyway.
