### ISSUE TITLE
Latest version of R

### ISSUE THREAD

**Issue by RosaEllis** [munichrocker/DatawRappr#54]
First of all, thank you for writing this package, it is extremely helpful. I upgraded my R recently and the package doesn't seem to work with the latest version of R (4.0.3). I just wondered if you have any plans to update the package to work with the latest version of R?

**Comment by trekonom** [comment]
Probably not related to R 4.0.3. I installed DatawRappr some days ago and it's running fine with R 4.0.3 on my machine.

**Comment by munichrocker** [comment]
I'm sorry folks, I didn't have the time to update R yet. But I guess, this might not be an DatawRappr issue - if I get @trekonom right?

**Comment by edorare** [comment]
Hi @munichrocker, I'm facing the same issue. Did you manage resolve it?

**Comment by munichrocker** [comment]
Alright, I finally had the time to update R and R-Studio. Datawrappr still works fine under my Mac High Sierra.

Could you specify you issues with an operating system and an error message, @edorare @RosaEllis?

**Comment by munichrocker** [comment]
As I've just updated my OS, the package works fine under Big Sur, and I haven't heard back - I will now close this issue for now. Feel free to let me know, if there are any remaining problems - then we can open it up again.
