### ISSUE TITLE
dw_list_charts() returns an error when some fields are NULL or lists

### ISSUE THREAD

**Issue by trekonom** [munichrocker/DatawRappr#65]
Hi Benedict,
thanks for `DatawRappr` which gave me a quick start to play around with the Datawrapper API in R.

I stumbled over an issue with `dw_list_charts`:
``` r
DatawRappr::dw_list_charts()
#> Error in (function (..., deparse.level = 1, make.row.names = TRUE, stringsAsFactors = FALSE, : invalid list argument: all variables should have the same length
```
<sup>Created on 2021-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I tracked down the issue to `DatawRappr:::bind_rows` (or `rbind.data.frame`) which fails if elements of a chart list are

* NULL (in my case e.g. `folderId` or `publishedAt`):

``` r
x <- list(
  list(publicId = "wuTKT", folderId = NULL)
)
DatawRappr:::bind_rows(x)
#> Error in (function (..., deparse.level = 1, make.row.names = TRUE, stringsAsFactors = FALSE, : invalid list argument: all variables should have the same length
```

<sup>Created on 2021-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

* are lists (in my case e.g. `thumbnails`):

``` r
x <- list(
  list(publicId = "wuTKT", folderId = NA, thumbnails = list(full = "foo", plain = "bar"))
)
DatawRappr:::bind_rows(x)
#> Error in (function (..., deparse.level = 1, make.row.names = TRUE, stringsAsFactors = FALSE, : invalid list argument: all variables should have the same length
```

<sup>Created on 2021-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by acmuehlhausen-smc** [comment]
Hey, 

while testing `Datawrapper` with your `DatawRappr` (thanks for the package!) I found, that this issue is still unresolved (or has other issues). If I run it on a newly created account (therefore no plots published etc.) I get the following error:

```
Error in (function (..., deparse.level = 1, make.row.names = TRUE, stringsAsFactors = FALSE,  : 
  invalid list argument: all variables should have the same length
In addition: Warning message:
'default.stringsAsFactors' is deprecated.
Use '`stringsAsFactors = FALSE`' instead.
``` 

Haven't had the time to dive in, yet. Would be glad, if this issue could be fixed, though list folders functions as a workaround.

Cheers!

**Comment by munichrocker** [comment]
Possible solution deployed with https://github.com/munichrocker/DatawRappr/tree/fix%2365/dw_list_charts. Needs some testing.

**Comment by trekonom** [comment]
Sorry for the super late reply. I checked and can confirm that the fix is working.
