### ISSUE TITLE
dw_publish_chart() failed with 403

### ISSUE THREAD

**Issue by ulrikeniemann** [munichrocker/DatawRappr#68]
Hello,
love to work with DatawRappr, most functions works but some not: 
(same problem on two different windows-computers)

**dw_list_charts()                   # Request failed [403]
dw_publish_chart()              # Request failed [403] 
dw_export_chart()               # Request failed [403]** 
dw_list_folders()                  # works
dw_create_chart()               # works
dw_copy_chart()                  # works
dw_delete_chart()               # works
dw_data_to_chart()            # works
dw_retrieve_chart_metadata()      # works
dw_edit_chart()                   # works

```
> # (re-)publish chart:
> dw_publish_chart("xxx") # Error 403
Request failed [403]. Retrying in 1.6 seconds...
Request failed [403]. Retrying in 3.3 seconds...
Error in dw_call_api("POST", url, httr::add_headers(Authorization = paste("Bearer",  : 
  There has been an error in an API call. Statuscode of the response: 403TRUE
```

My session Infos:

```
> print(sessionInfo())
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DatawRappr_1.2

loaded via a namespace (and not attached):
 [1] httr_1.4.7        compiler_4.2.2    magrittr_2.0.3    R6_2.5.1         
 [5] magick_2.7.5      cli_3.6.0         tools_4.2.2       rstudioapi_0.14  
 [9] curl_5.0.2        Rcpp_1.0.10       data.table_1.14.8 rlist_0.4.6.2    
[13] jsonlite_1.8.7    lifecycle_1.0.3   rlang_1.1.1      
```

**Comment by munichrocker** [comment]
Thanks for raising this issue.

At the moment, I cannot confirm an error that causes the issues above. I can run these commands:
`dw_publish_chart()` and `dw_export_chart()`. 

Another error comes up with `dw_list_charts()` that is already mentioned here: https://github.com/munichrocker/DatawRappr/issues/65 (workaround seems to be `dw_list_folders()`).

However, there might be some limitations caused by the setup of the API key that is used: https://developer.datawrapper.de/docs

**Comment by munichrocker** [comment]
The issue author has confirmed that the solution mentioned below solved the issue:

https://github.com/munichrocker/DatawRappr/issues/68#issuecomment-1719424139
